# Path to regional annotation in GeoJSON format  
input: ./input/regional_annotation.json

# image file name from DSA
image_filename: 2551571.svs
  
# path to write converted json annotations
output_folder: ./dsa_annotations/

# annotation name to be shown in DSA  
annotation_name: Regional Annotation

# line and fill colors in label:rgb/a format
line_colors:
  lympho_rich_tumor: rgb(0,191,255)
  lympho_poor_tumor: rgb(0,255,0)
  necrosis: rgb(255,255,0)
  lympho_rich_stroma: rgb(255,0,0)
  veins: rgb(0,255,255)
  adipocytes: rgb(0,0,255)
  qc_tissue_fold: rgb(0,0,0)
  
fill_colors:
  lympho_rich_tumor: rgb(0,191,255,100)
  lympho_poor_tumor: rgb(0,255,0,100)
  necrosis: rgb(255,255,0,100)
  lympho_rich_stroma: rgb(255,0,0,100)
  veins: rgb(0,255,255,100)
  adipocytes: rgb(0,0,255,100)
  qc_tissue_fold: rgb(0,0,0,100)

