# path to DSA compatible annotation    
annotation_filepath: ./dsa_annotations/Points_of_Classsified_StarDist_Cells_HobI20-681330526186.json
    
# image file name from DSA
image_filename: HobI20-681330526186.svs
    
# collection name from DSA
collection_name: test-path

