codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "85...100"

ignore:
  - "pyluna-common/tests/**/*"
  - "pyluna-core/tests/**/*"
  - "pyluna-pathology/tests/**/*"
  - "pyluna-pathology/luna/pathology/examples/*"
  - "pyluna-radiology/tests/**/*"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

fixes:
   - "/home/circleci/::"
