repos:
-   repo: https://github.com/psf/black.git
    rev: 22.1.0
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
    - id: flake8

