exclude: '.archive|docker'
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.9
      args: [--line-length=88, --exclude="setup.py"]
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      exclude: breastana/__init__.py
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
        - id: pydocstyle
          args: [--convention=numpy, --match=src/luna/*.py]
