# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf

conda:
  environment: environment.yml

# https://docs.readthedocs.io/en/stable/config-file/v2.html#build-apt-packages
build:
  os: ubuntu-20.04
  apt_packages:
     - libblas-dev
     - liblapack-dev
     - gfortran
     - libgdal-dev
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_create_environment:
      - poetry config virtualenvs.create false --local
      - SETUPTOOLS_USE_DISTUTILS=stdlib poetry install
      - export LUNA_HOME=$PWD
