# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf

# https://docs.readthedocs.io/en/stable/config-file/v2.html#build-apt-packages
build:
  os: ubuntu-20.04
  apt_packages:
     - libblas-dev
     - liblapack-dev
     - gfortran
     - openslide-tools
     - python-openslide
     - libgdal-dev
  tools:
    python: "3.9"

# Optionally set the version of Python and requirements required to build your docs
python:
    #version: "3.9"
   install:
   - requirements: docs/requirements_extra.txt # for numpy dep.
   - requirements: requirements_dev.txt
