version: 2.1

# ideas for the future:
# @todo https://circleci.com/docs/2.0/workflows/
# @todo https://github.com/features/actions (github actions are similar to circleci and works for also forked repos)
# docker-compose integration testing in circleci
# kubernetes deploy and integration test
# usecase focussed integration tests if code changes frequently

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    parallelism: 2
    docker:
      - image: circleci/python:3.6.8  # primary container for the build job

    steps:
      - checkout
      - run: cat /etc/os-release
      - run: sudo apt update
      - run: sudo apt install openslide-tools python-openslide default-jre
      - run: java -version
      - run: which java
      - run: echo "export PATH=/home/circleci/.local/bin:$PATH" >> $BASH_ENV  # some python packages get installed  here
      - run: echo "export CODECOV_TOKEN="4d2ae912-4489-4e40-ac13-02add6c0d1a6"" >> $BASH_ENV
      - run: echo "export LUNA_HOME=pyluna-common/tests/luna/common/testdata" >> $BASH_ENV
      - run: echo "export PYTHONPATH=.:src:pyluna-common:pyluna-radiology:pyluna-pathology" >> $BASH_ENV
      - run: export PYSPARK_PYTHON=`which python`
      - run: echo $PATH
      - run: python --version
      - run: sudo pip install --upgrade pip
      - run: pip --version
      - run: sudo pip install -r requirements_dev.txt -q
      - run: pip list
      - run: pip check
      #- run: sudo python setup.py install  # needed to run the cli unit tests
      - run: pytest -v --capture=tee-sys --show-capture=all --cov=pyluna-common pyluna-common/tests --cov-report=xml
      - run: pytest -v --capture=tee-sys --show-capture=all --cov=pyluna-radiology pyluna-radiology/tests --cov-report=xml --cov-append
      - run: pytest -v --capture=tee-sys --show-capture=all --cov=pyluna-pathology pyluna-pathology/tests --cov-report=xml --cov-append
      - run: coverage report -m
      - store_artifacts:
          path: htmlcov
      - codecov/upload:
          file: coverage.xml
