FROM python:3.9-slim

ARG USER_NAME
ENV user=$USER_NAME
ARG USER_ID
ARG GROUP_NAME
ARG GROUP_ID

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl git \
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# so host system user can delete files created by this container
RUN groupadd $GROUP_NAME
RUN useradd -l -rm -d /home/$USER_NAME -s /bin/bash -g $GROUP_NAME -u $USER_ID $USER_NAME
WORKDIR /home/$USER_NAME
ENV PATH=$PATH:/home/$USER_NAME/.local/bin

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -LJ https://github.com/krallin/tini/releases/download/v0.19.0/tini -o /usr/bin/tini && \
    chmod +x /usr/bin/tini

RUN python -m pip install --upgrade pip

# lock down versions for build stability
RUN python -m pip install --pre --no-cache-dir \
    packaging==21.3 \
    histomicsui==1.3.1.dev183 \
    large_image[sources]==1.15.1.dev2 \
    # girder[mount] adds dependencies to show tiles from S3 assets \
    girder[mount]==3.1.15.dev2 \
    girder-homepage==3.1.15.dev2 \
    girder_client==3.1.15.dev2 \
    --find-links https://girder.github.io/large_image_wheels

RUN girder build

COPY girder.cfg /etc/.

ENTRYPOINT ["/usr/bin/tini", "--"]

RUN mkdir /logs && chmod -R 777 /logs
USER $USER_NAME


# provision_girder.py -
#  - creates an admin user with root credentials admin:password1
#  - Downloads svs images from https://data.kitware.com/#user/61b9f3dc4acac99f42ca7678/folder/61b9f4564acac99f42ca7692
#      and saves the slides at ~/vmount/PRO-12-123/data/toy_data_set
#  - Creates an assetstore at ~/vmount/assetstore
#  - Organizes the sample images in TCGA collection
#  - Uploads annotations to the slides.

CMD python vmount/provision_girder.py --sample-data --user $user && girder serve --database mongodb://mongodb:27017/girder
