FROM python:3.9-slim

ARG user
ENV user=$user

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# so host system user can delete files created by this container
RUN useradd -m -s /bin/bash -G sudo $user && echo "$user:docker"

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -LJ https://github.com/krallin/tini/releases/download/v0.19.0/tini -o /usr/bin/tini && \
    chmod +x /usr/bin/tini

RUN python -m pip install --pre --no-cache-dir \
    histomicsui \
    large_image[sources] \
    # girder[mount] adds dependencies to show tiles from S3 assets \
    girder[mount] \
    girder-homepage \
    girder_client \
    --find-links https://girder.github.io/large_image_wheels

RUN girder build

COPY girder.cfg /etc/.

ENTRYPOINT ["/usr/bin/tini", "--"]

CMD girder serve --database mongodb://mongodb:27017/girder