FROM python:3.9-slim

## supress interactive dialogs
ARG DEBIAN_FRONTEND=noninteractive

ARG USER_ID
ARG GROUP_ID
ARG USER_NAME
ARG GROUP_NAME
RUN echo $USER_ID:$GROUP_ID $USER_NAME:$GROUP_NAME

## install OS dependencies
RUN apt-get update
RUN apt-get install build-essential libgdal-dev libgl1 software-properties-common openslide-tools python3-openslide git vim curl tree -y 

## create user so python packages are not being installed with root and jupyter is not executed with rootr
## map host user to container user so files can be easily accessed from host and container
RUN groupadd $GROUP_NAME
RUN useradd -l -rm -d /home/$USER_NAME -s /bin/bash -g $GROUP_NAME -u $USER_ID $USER_NAME
USER $USER_NAME
WORKDIR /home/$USER_NAME
ENV PATH=$PATH:/home/$USER_NAME/.local/bin

# install luna
## Set pip timeout error
ENV PIP_DEFAULT_TIMEOUT=100

## Install everything
RUN python3 -m pip install --no-cache-dir --user --upgrade pip pytest
RUN python3 -m pip install histomicstk --find-links https://girder.github.io/large_image_wheels && python3 -m pip install pyluna[pathology]
RUN python3 -m pip install --no-cache-dir jupyter

## set env vars
ENV LUNA_HOME="/home/$USER_NAME/vmount"
ENV LANG="C.UTF-8"

## verify installation
RUN echo $LUNA_HOME
RUN which jupyter
RUN pip list | grep luna
RUN python3 -c 'import luna; import luna.common; import luna.pathology'

# Ideally we want to remove the need to do this, maybe?
COPY vmount/conf/logging.cfg "/home/$USER_NAME/vmount/conf/logging.cfg"
#COPY vmount/conf/datastore.cfg "/home/$USER_NAME/vmount/conf/datastore.cfg" 

RUN python3 -m pip install pyradiomics tqdm staintools requests_mock
RUN python3 --version

RUN git clone https://github.com/msk-mind/luna.git && cd luna && git checkout tags/v0.3.2 && pytest pyluna-pathology/tests

## entrypoint # more flexibility
#CMD jupyter notebook --ip 0.0.0.0 --notebook-dir=~/vmount
#CMD jupyter notebook --ip 0.0.0.0 --notebook-dir=~/vmount/notebooks
