FROM python:3.9-slim

## supress interactive dialogs
ARG DEBIAN_FRONTEND=noninteractive

ARG USER_ID
ARG GROUP_ID
ARG USER_NAME
ARG GROUP_NAME
ARG LUNA_VERSION
RUN echo $USER_ID:$GROUP_ID $USER_NAME:$GROUP_NAME
RUN echo Installing luna v$LUNA_VERSION
## install OS dependencies
RUN apt-get update
RUN apt-get install build-essential libgdal-dev libgl1 software-properties-common openslide-tools python3-openslide git vim curl tree -y 

## create user so python packages are not being installed with root and jupyter is not executed with rootr
## map host user to container user so files can be easily accessed from host and container
RUN groupadd $GROUP_NAME
RUN useradd -l -rm -d /home/$USER_NAME -s /bin/bash -g $GROUP_NAME -u $USER_ID $USER_NAME
USER $USER_NAME
WORKDIR /home/$USER_NAME
ENV PATH=$PATH:/home/$USER_NAME/.local/bin

# install luna
## Set pip timeout error
ENV PIP_DEFAULT_TIMEOUT=100

## Install everything
RUN python3 -m pip install --no-cache-dir --user --upgrade pip pytest
RUN python3 -m pip install histomicstk --find-links https://girder.github.io/large_image_wheels

RUN git clone https://github.com/msk-mind/luna.git
RUN cd luna && git checkout dev && cd pyluna-common  && python3 -m pip install -e .
RUN cd luna && git checkout dev && cd pyluna-pathology && python3 -m pip install -e .
RUN python3 -m pip install --no-cache-dir jupyter

## set env vars
ENV LUNA_HOME="/home/$USER_NAME/vmount"
ENV LANG="C.UTF-8"

## verify installation
RUN echo $LUNA_HOME
RUN which jupyter
RUN pip list | grep luna
RUN python3 -c 'import luna; import luna.common; import luna.pathology'

# Ideally we want to remove the need to do this, maybe?
COPY vmount/conf/logging.cfg "/home/$USER_NAME/vmount/conf/logging.cfg"

RUN python3 -m pip install requests_mock testfixtures
RUN cd luna && git checkout tags/v$LUNA_VERSION && pytest pyluna-pathology/tests && pytest pyluna-common/tests

## entrypoint (see docker-compose file)
