rule all:
    input: "../outputs/visualize_tiles.done", "../outputs/infer_tiles.done"
    
rule visualize_tiles:
    input: "../model/outputs/ckpts/", "../tiles/2551129/ov_default_labels/TileImages/data",
    output: touch("../outputs/visualize_tiles.done"),
    log: "../logs/visualize_tiles.log",
    shell: "visualize_tiles -a ../../configs/snakemake-configs/app_config.yaml -s 2551129 -m ../../configs/snakemake-configs/visualize_tiles.yaml"
    
rule infer_tiles:
    input:  "../model/outputs/ckpts/", "../tiles/2551129/ov_default_labels/TileImages/data",
    output: touch("../outputs/infer_tiles.done"),
    log: "../logs/infer_tiles.log",
    shell: "infer_tiles -a ../../configs/snakemake-configs/app_config.yaml -s 2551129 -m ../../configs/snakemake-configs/infer_tiles.yaml"
    
rule train_model:
    input: "../outputs/collect_tiles_train.done",
    output: touch("../outputs/train_model.done"), directory("../model/outputs/ckpts/"),
    log: "../logs/train_model.log",
    script: "../scripts/train_model.py"

rule collect_tiles_train:
    input: "../tiles/2551571/ov_default_labels/TileImages/data",
    output: touch("../outputs/collect_tiles_train.done"),
    log: "../logs/collect_tiles_train.log",
    script: "../scripts/collect_tiles_train.py"
    
rule generate_tiles_test:
    input: "../tiles/2551571/ov_slides/WholeSlideImage/",
    output: touch("../outputs/generate_tiles_test.done"), directory("../tiles/2551129/ov_default_labels/TileImages/data"),
    log: "../logs/generate_tiles_test.log",
    shell: "generate_tiles -a ../../configs/snakemake-configs/app_config.yaml -s 2551129 -m ../../configs/snakemake-configs/generate_tiles_test.yaml"
    
rule generate_tiles_train:
    input: "../tiles/2551571/ov_slides/WholeSlideImage/",
    output: touch("../outputs/generate_tiles_train.done"), directory("../tiles/2551571/ov_default_labels/TileImages/data"),
    log: "../logs/generate_tiles_train.log",
    script: "../scripts/generate_tiles_train.py"
    
rule update_patient_ids:
    input: "/gpfs/mskmindhdp_emc/user/shared_data_folder/pathology-tutorial/configs/snakemake-configs/project_slides.csv",
    output: touch("../outputs/update_patient_ids.done"),
    log: "../logs/update_patient_ids.log",
    script: "../scripts/update_patient_ids.py"
    
rule load_slides:
    input: "../outputs/update_patient_ids.done",
    output: directory("../tiles/2551571/ov_slides/WholeSlideImage/"), touch("../outputs/load_slides.done"),
    log: "../logs/load_slides.log",
    script: "../scripts/load_slides.py"

rule regional_annotation_etl:
    input: "/gpfs/mskmindhdp_emc/user/shared_data_folder/pathology-tutorial/configs/snakemake-configs/project_slides.csv",
    output: directory("../data/regional-annotations"), touch("../outputs/regional_annotation_etl.done")
    log: "../logs/regional_annotation_etl.log",
    shell: "python3 -m data_processing.pathology.refined_table.regional_annotation.dask_generate \
            -d ../../configs/snakemake-configs/regional_annotation_config.yaml \
            -a ../../configs/snakemake-configs/app_config.yaml"

rule build_proxy_table:
    input: "/gpfs/mskmindhdp_emc/user/shared_data_folder/pathology-tutorial/snakemake/data/snakemake_toy_data_set/",
    output: directory("../data/snakemake_PRO_12-123"), touch("../outputs/build_proxy_table.done")
    log: "../logs/build_proxy_table.log",
    shell: "python3 -m data_processing.pathology.proxy_table.generate \
            -d ../../configs/snakemake-configs/wsi_config.yaml \
            -a ../../configs/snakemake-configs/app_config.yaml \
            -p delta"
    